services:
  web:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/web/config/nginx.conf:/etc/nginx/nginx.conf
      - ./mobile-ui/dist:/usr/share/nginx/html
    networks:
      - net-frontend
      - net-backend
    extra_hosts:
      - host.docker.internal:host-gateway

  was01:
    image: tomcat
    container_name: was01
    ports:
      - "10001:8080"
    volumes:
      - ./deploy/was01/webapps/:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - web
    networks:
      - net-backend
  was02:
    image: tomcat
    container_name: was02
    ports:
      - "10002:8080"
    volumes:
      - ./deploy/was02/webapps/:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - web
    networks:
      - net-backend

  app01:
    image: app:1.0
    container_name: app01
    ports:
      - "10003:8080"
    depends_on:
      - mysql
    networks:
      - net-backend
    restart: on-failure
  app02:
    image: app:1.0
    container_name: app02
    ports:
      - "10004:8080"
    depends_on:
      - mysql
    networks:
      - net-backend
    restart: on-failure

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw1234
    ports:
      - "3306:3306"
    networks:
      - net-backend

networks:
  net-frontend:
  net-backend: